export const proteins = [
  "Almond",
  "Anchovies",
  "Bacon",
  "Beef brisket",
  "Beef rib",
  "Bison",
  "Black beans",
  "Bratwurst",
  "Breakfast sausage",
  "Cashew",
  "Cheese",
  "Chicken breast",
  "Chicken thigh",
  "Chickpeas",
  "Chorizo",
  "Clams",
  "Cod",
  "Crab",
  "Duck breast",
  "Edamame",
  "Eggs",
  "Feta cheese",
  "Flounder",
  "Goat",
  "Ground beef",
  "Ground lamb",
  "Ground pork",
  "Ground turkey",
  "Halibut",
  "Italian sausage",
  "Kidney beans",
  "Kielbasa",
  "Lamb chops",
  "Lentils",
  "Lobster",
  "Navy beans",
  "Octopus",
  "Paneer",
  "Pinto beans",
  "Plant-based meat",
  "Pork belly",
  "Pork chop",
  "Prosciutto",
  "Salami",
  "Salmon",
  "Sardines",
  "Sausage",
  "Scallops",
  "Seitan",
  "Shrimp",
  "Snapper",
  "Steak",
  "Swordfish",
  "Tempeh",
  "Tilapia",
  "Tofu",
  "Trout",
  "Tuna",
  "Turkey breast",
  "White beans",
  "Yellowfin tuna",
  // "Catfish",
  // "Bison",
  // "Catfish",
  // "Clams",
  // "Frog legs",
  // "Halibut",
  // "Mackerel",
  // "Mussels",
  // "Pheasant",
  // "Pigeon",
  // "Quail",
  // "Rabbit",
  // "Venison",
];

export const vegetables = [
  "Acorn squash",
  "Artichoke",
  "Arugula",
  "Asparagus",
  "Avocado",
  "Bamboo shoot",
  "Beet",
  "Bell pepper",
  "Bok choy",
  "Broccoli",
  "Brussel sprouts",
  "Butternut squash",
  "Cabbage",
  "Carrot",
  "Cauliflower",
  "Celery",
  "Cherry tomato",
  "Chili pepper",
  "Chive",
  "Collard green",
  "Collard green",
  "Corn",
  "Cucumber",
  "Daikon",
  "Eggplant",
  "Endive",
  "Fennel",
  "Frisée",
  "Garlic",
  "Green bean",
  "Green onion",
  "Horseradish",
  "Jicama",
  "Kale",
  "Kohlrabi",
  "Leek",
  "Lettuce",
  "Mushroom",
  "Mustard green",
  "Napa cabbage",
  "Okra",
  "Olive",
  "Onion",
  "Parsnip",
  "Peas",
  "Portobello mushroom",
  "Pumpkin",
  "Radicchio",
  "Radish",
  "Rainbow chard",
  "Ramps",
  "Red cabbage",
  "Red onion",
  "Rutabaga",
  "Scallion",
  "Seaweed",
  "Shallot",
  "Snow peas",
  "Spaghetti squash",
  "Spinach",
  "Sprouts",
  "Sugar snap peas",
  "Sweet potato",
  "Swiss chard",
  "Tomatillo",
  "Tomato",
  "Turnip",
  "Watercress",
  "Zucchini",
];

export const seasonings = [
  "Adobo",
  "Agave syrup",
  "Aji Amarillo paste",
  "Allspice",
  "Anise seeds",
  "Apple cider vinegar",
  "Balsamic vinegar",
  "Barbecue sauce",
  "Basil",
  "Bay leaves",
  "Black garlic",
  "Black pepper",
  "Bone broth",
  "Brown sugar",
  "Butter",
  "Cacao nibs",
  "Caraway seeds",
  "Cardamom",
  "Cayenne pepper",
  "Celery salt",
  "Celery seed",
  "Chervil",
  "Chili powder",
  "Chimichurri sauce",
  "Chinese five-spice",
  "Chipotle powder",
  "Chutney",
  "Cilantro",
  "Cinnamon",
  "Clarified butter",
  "Cloves",
  "Cocoa powder",
  "Coconut aminos",
  "Coriander",
  "Creme fraiche",
  "Creole seasoning",
  "Cumin",
  "Curry leaves",
  "Curry powder",
  "Dashi",
  "Dijon mustard",
  "Dill",
  "Fennel seeds",
  "Fenugreek",
  "Fish sauce",
  "Galangal",
  "Garam masala",
  "Garlic powder",
  "Ghee",
  "Ginger",
  "Gochugaru",
  "Green curry paste",
  "Harissa",
  "Herbes de Provence",
  "Hoisin sauce",
  "Honey",
  "Horseradish",
  "Hot sauce",
  "Italian seasoning",
  "Jamaican jerk seasoning",
  "Kaffir lime leaves",
  "Kimchi",
  "Lavender",
  "Lemon juice",
  "Lemon zest",
  "Lemongrass",
  "Lime juice",
  "Lime zest",
  "Liquid smoke",
  "Mace",
  "Malt vinegar",
  "Maple syrup",
  "Mint",
  "Mirin",
  "Miso",
  "Mustard seeds",
  "Nori flakes",
  "Nutmeg",
  "Nutritional yeast",
  "Onion powder",
  "Orange juice",
  "Orange zest",
  "Oregano",
  "Paprika",
  "Parsley",
  "Peanut butter",
  "Pink peppercorns",
  "Poppy seeds",
  "Preserved lemon",
  "Red pepper flakes",
  "Red wine vinegar",
  "Rice vinegar",
  "Rosemary",
  "Saffron",
  "Sage",
  "Sesame oil",
  "Sesame seeds",
  "Sherry vinegar",
  "Sichuan peppercorns",
  "Smoked paprika",
  "Smoked salt",
  "Soy sauce",
  "Star anise",
  "Sumac",
  "Sweet chili sauce",
  "Tahini",
  "Tamarind paste",
  "Tarragon",
  "Thai basil",
  "Thyme",
  "Toasted sesame oil",
  "Togarashi",
  "Truffle oil",
  "Turmeric",
  "Umeboshi vinegar",
  "Worcestershire sauce",
  "Za'atar",
];

export const preparations = [
  "Arepas",
  "Baked",
  "Bao buns",
  "Barbecued",
  "Bibimbap",
  "Biryani",
  "Braised",
  "Buddha bowl",
  "Burrito",
  "Carpaccio",
  "Casserole",
  "Ceviche",
  "Chili",
  "Crepes",
  "Curry",
  "Dim sum",
  "Dip",
  "Empanadas",
  "Enchiladas",
  "Falafel wrap",
  "Flatbread",
  "Focaccia",
  "Fondue",
  "Fried",
  "Frittata",
  "Galette",
  "Gnocchi",
  "Grilled",
  "Gumbo",
  "Hotpot",
  "Hummus plate",
  "Jambalaya",
  "Jollof rice",
  "Kebabs",
  "Moussaka",
  "Nachos",
  "Omelette",
  "Over rice",
  "Paella",
  "Pasta",
  "Pho",
  "Pierogis",
  "Pita wrap",
  "Pizza",
  "Poached",
  "Poke bowl",
  "Polenta",
  "Pot pie",
  "Pozole",
  "Quesadilla",
  "Ramen",
  "Ratatouille",
  "Risotto",
  "Roasted",
  "Salad",
  "Sandwich",
  "Sashimi",
  "Shakshuka",
  "Soup",
  "Spring rolls",
  "Steamed",
  "Stew",
  "Stir fry",
  "Stuffed grape leaves",
  "Stuffed peppers/mushrooms/etc",
  "Sushi",
  "Tabbouleh",
  "Tacos",
  "Tagine",
  "Tapas",
  "Tostadas",
  "Broiled",
  "Calzone",
  "Chimichanga",
  "Chowder",
  "Congee",
  "Croquettes",
  "Dumplings",
  "Egg rolls",
  "Fajitas",
  "Fried rice",
  "Fritters",
  "Gazpacho",
  "Gratin",
  "Burger",
  "Hash",
  "Lasagna",
  "Lettuce wraps",
  "Meatballs",
  "Panini",
  "Patty",
  "Pilaf",
  "Pot stickers",
  "Quiche",
  "Samosas",
  "Scalloped",
  "Scramble",
  "Skewers",
  "Sliders",
  "Tempura",
  "Melt",
  "Waffles",
];
