export const proteins = [
  "Anchovies",
  "Black beans",
  "Chicken breast",
  "Chicken thigh",
  "Chickpeas",
  "Cod",
  "Crab",
  "Duck breast",
  "Edamame",
  "Eggs",
  "Goat",
  "Ground beef",
  "Ground lamb",
  "Ground pork",
  "Ground turkey",
  "Kidney beans",
  "Lamb chops",
  "Lentils",
  "Lobster",
  "Navy beans",
  "Pinto beans",
  "Plant-based meat substitutes",
  "Pork belly",
  "Pork chop",
  "Salmon",
  "Sardines",
  "Scallops",
  "Seitan",
  "Shrimp",
  "Steak",
  "Tempeh",
  "Tilapia",
  "Tofu",
  "Tuna",
  "Turkey breast",
  // "Bison",
  // "Catfish",
  // "Clams",
  // "Frog legs",
  // "Halibut",
  // "Mackerel",
  // "Mussels",
  // "Pheasant",
  // "Pigeon",
  // "Quail",
  // "Rabbit",
  // "Venison",
];

export const vegetables = [
  "Artichoke",
  "Arugula",
  "Asparagus",
  "Avocado",
  "Bamboo shoot",
  "Beet",
  "Bell pepper",
  "Bok choy",
  "Broccoli",
  "Brussels sprout",
  "Butternut squash",
  "Cabbage",
  "Carrot",
  "Cauliflower",
  "Celery",
  "Cherry tomato",
  "Collard green",
  "Corn",
  "Cucumber",
  "Daikon",
  "Eggplant",
  "Fennel",
  "Garlic",
  "Green bean",
  "Green onion",
  "Horseradish",
  "Jicama",
  "Kale",
  "Leek",
  "Lettuce",
  "Mushroom",
  "Mustard green",
  "Okra",
  "Onion",
  "Parsnip",
  "Peas",
  "Pumpkin",
  "Radish",
  "Red onion",
  "Rutabaga",
  "Seaweed",
  "Shallot",
  "Snow peas",
  "Spinach",
  "Sprout",
  "Sugar snap peas",
  "Sweet potato",
  "Swiss chard",
  "Tomato",
  "Turnip",
  "Watercress",
  "Zucchini",
  // "Chayote",
];

export const seasonings = [
  "Agave syrup",
  "Allspice",
  "Anise seeds",
  "Apple cider vinegar",
  "Balsamic vinegar",
  "Basil",
  "Bay leaves",
  "Black garlic",
  "Black pepper",
  "Bone broth",
  "Caraway seeds",
  "Cardamom",
  "Cayenne pepper",
  "Chervil",
  "Chili powder",
  "Chinese five-spice",
  "Cilantro",
  "Cinnamon",
  "Clarified butter",
  "Cloves",
  "Coconut aminos",
  "Coriander",
  "Cumin",
  "Curry powder",
  "Dashi",
  "Dill",
  "Fennel seeds",
  "Fenugreek",
  "Fish sauce",
  "Galangal",
  "Garam masala",
  "Garlic powder",
  "Ghee",
  "Ginger",
  "Gochugaru",
  "Harissa",
  "Herbes de Provence",
  "Honey",
  "Italian seasoning",
  "Kaffir lime leaves",
  "Lavender",
  "Lemon juice",
  "Lemon zest",
  "Lemongrass",
  "Lime juice",
  "Lime zest",
  "Liquid smoke",
  "Mace",
  "Malt vinegar",
  "Maple syrup",
  "Mint",
  "Mirin",
  "Miso",
  "Mustard seeds",
  "Nutmeg",
  "Nutritional yeast",
  "Onion powder",
  "Orange juice",
  "Orange zest",
  "Oregano",
  "Paprika",
  "Parsley",
  "Peanut butter",
  "Red wine vinegar",
  "Rice vinegar",
  "Rosemary",
  "Saffron",
  "Sage",
  "Sesame oil",
  "Sherry vinegar",
  "Smoked paprika",
  "Smoked salt",
  "Soy sauce",
  "Sumac",
  "Tahini",
  "Tarragon",
  "Thai basil",
  "Thyme",
  "Togarashi",
  "Truffle oil",
  "Turmeric",
  "Umeboshi vinegar",
  "Worcestershire sauce",
  "Za'atar",
  // "Almond extract",
  // "Duck fat",
  // "Orange blossom water",
  // "Peppermint",
  // "Rosewater",
  // "Salt",
  // "Spearmint",
  // "Vanilla extract",
];

export const preparations = [
  "Arepas",
  "Baked",
  "Bao buns",
  "Barbecued",
  "Bibimbap",
  "Biryani",
  "Braised",
  "Buddha bowl",
  "Burrito",
  "Carpaccio",
  "Casserole",
  "Ceviche",
  "Chili",
  "Crepes",
  "Curry",
  "Dim sum",
  "Dip",
  "Empanada",
  "Enchiladas",
  "Falafel wrap",
  "Flatbread",
  "Focaccia",
  "Fondue",
  "Fried",
  "Frittata",
  "Galette",
  "Gnocchi",
  "Grilled",
  "Gumbo",
  "Hotpot",
  "Hummus plate",
  "Jambalaya",
  "Jollof rice",
  "Kebabs",
  "Moussaka",
  "Nachos",
  "Omelette",
  "Over rice",
  "Paella",
  "Pasta",
  "Pho",
  "Pierogi",
  "Pita wrap",
  "Pizza",
  "Poached",
  "Poke bowl",
  "Polenta",
  "Pot pie",
  "Pozole",
  "Quesadilla",
  "Ramen",
  "Ratatouille",
  "Risotto",
  "Roasted",
  "Salad",
  "Sandwich",
  "Sashimi",
  "Shakshuka",
  "Soup",
  "Spring rolls",
  "Steamed",
  "Stew",
  "Stir fry",
  "Stuffed grape leaves",
  "Stuffed peppers/mushrooms/etc",
  "Sushi",
  "Tabbouleh",
  "Taco",
  "Tagine",
  "Tapas",
  "Tostadas",
  // "Bagel sandwich",
  // "Breakfast burrito",
  // "Tarte flambée",
];
