export const proteins = [
  "Chicken breast",
  "Chicken thigh",
  "Ground beef",
  "Steak",
  "Pork chop",
  "Pork belly",
  "Ground pork",
  "Turkey breast",
  "Ground turkey",
  "Duck breast",
  "Lamb chops",
  "Lamb ground",
  "Salmon",
  "Tuna",
  "Cod",
  "Shrimp",
  "Scallops",
  "Crab",
  // "Lobster",
  "Tofu",
  "Tempeh",
  "Seitan",
  "Eggs",
  "Sardines",
  // "Clams",
  // "Mussels",
  // "Venison",
  // "Bison",
  // "Rabbit",
  // "Halibut",
  // "Catfish",
  // "Mackerel",
  "Tilapia",
  "Anchovies",
  // "Quail",
  // "Pigeon",
  // "Pheasant",
  "Goat",
  "Plant-based meat substitutes",
  // "Frog legs",
  "Chickpeas",
  "Black beans",
  "Kidney beans",
  "Lentils",
  "Pinto beans",
  "Navy beans",
  "Edamame",
  // "Green peas",
];

export const vegetables = [
  "Broccoli",
  "Cauliflower",
  "Carrot",
  "Spinach",
  "Kale",
  "Zucchini",
  "Bell pepper",
  "Onion",
  "Garlic",
  "Asparagus",
  "Green bean",
  "Snow peas",
  "Sugar snap peas",
  "Cabbage",
  "Brussels sprout",
  "Eggplant",
  "Mushroom",
  "Sweet potatoe",
  "Butternut squash",
  "Beet",
  "Radish",
  "Tomato",
  "Cucumber",
  "Celery",
  "Lettuce",
  "Arugula",
  "Watercress",
  "Fennel",
  "Artichoke",
  "Leek",
  "Shallot",
  "Corn",
  "Peas",
  "Okra",
  "Turnip",
  "Rutabaga",
  // "Chayote",
  "Bok choy",
  "Collard green",
  "Mustard green",
  "Swiss chard",
  "Pumpkin",
  "Jicama",
  "Daikon",
  "Bamboo shoot",
  "Seaweed",
  "Avocado",
  "Sprout",
  "Parsnip",
  "Horseradish",
];

export const seasonings = [
  // "Salt",
  "Black pepper",
  "Garlic powder",
  "Onion powder",
  "Paprika",
  "Smoked paprika",
  "Cumin",
  "Coriander",
  "Chili powder",
  "Cayenne pepper",
  "Turmeric",
  "Curry powder",
  "Garam masala",
  "Oregano",
  "Basil",
  "Thyme",
  "Rosemary",
  "Sage",
  "Dill",
  "Parsley",
  "Cilantro",
  "Bay leaves",
  "Fennel seeds",
  "Mustard seeds",
  "Caraway seeds",
  "Anise seeds",
  "Cardamom",
  "Cinnamon",
  "Nutmeg",
  "Cloves",
  "Allspice",
  "Ginger",
  "Saffron",
  "Sumac",
  "Za'atar",
  "Herbes de Provence",
  "Italian seasoning",
  "Chinese five-spice",
  "Harissa",
  "Gochugaru",
  "Shichimi Togarashi",
  "Miso",
  "Soy sauce",
  "Fish sauce",
  "Worcestershire sauce",
  "Balsamic vinegar",
  "Apple cider vinegar",
  "Red wine vinegar",
  "Rice vinegar",
  "Lemon zest",
  "Lime zest",
  "Orange zest",
  "Lemon juice",
  "Lime juice",
  "Orange juice",
  "Honey",
  "Maple syrup",
  "Agave syrup",
  "Tahini",
  "Peanut butter",
  "Black garlic",
  "Fenugreek",
  "Mace",
  "Tarragon",
  "Chervil",
  "Lavender",
  "Lemongrass",
  "Kaffir lime leaves",
  "Galangal",
  "Basil (Thai)",
  "Peppermint",
  "Spearmint",
  "Rosewater",
  "Orange blossom water",
  "Vanilla extract",
  "Almond extract",
  "Smoked salt",
  "Truffle oil",
  "Sesame oil",
  "Ghee",
  "Clarified butter",
  "Duck fat",
  "Bone broth",
  "Dashi",
  "Mirin",
  "Umeboshi vinegar",
  "Sherry vinegar",
  "Malt vinegar",
  "Coconut aminos",
  "Nutritional yeast",
  "Liquid smoke",
];

export const preparations = [
  "Over rice",
  "Stir fry",
  "Omelette",
  "Burrito",
  "Sushi",
  "Taco",
  "Sandwich",
  "Salad",
  "Soup",
  "Stew",
  "Casserole",
  "Pasta",
  "Pizza",
  "Grilled",
  "Roasted",
  "Braised",
  "Fried",
  "Baked",
  "Poached",
  "Steamed",
  "Barbecued",
  "Kebabs",
  "Frittata",
  "Pita wrap",
  "Flatbread",
  "Quesadilla",
  "Empanada",
  "Pot pie",
  "Curry",
  "Risotto",
  "Paella",
  "Tapas",
  "Dim sum",
  "Hotpot",
  "Stuffed peppers/mushrooms/etc",
  "Ceviche",
  "Carpaccio",
  "Sashimi",
  "Spring rolls",
  "Dip",
  "Fondue",
  "Tostadas",
  "Nachos",
  "Enchiladas",
  "Crepes",
  "Galette",
  "Ratatouille",
  "Tabbouleh",
  "Hummus plate",
  "Buddha bowl",
  "Ramen",
  "Pho",
  "Bibimbap",
  "Shakshuka",
  "Falafel wrap",
  "Gumbo",
  "Jambalaya",
  "Moussaka",
  "Biryani",
  "Tagine",
  "Jollof rice",
  "Pierogi",
  "Stuffed grape leaves",
  "Arepas",
  "Pozole",
  "Chili",
  "Gnocchi",
  "Polenta",
  "Focaccia",
  // "Bagel sandwich",
  // "Breakfast burrito",
  "Poke bowl",
  "Bao buns",
  // "Tarte flambée",
];
